[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tb_ml/tests",
]

[tool.mypy]
exclude = "docker|test_data|tests"
ignore_missing_imports = true
strict = true